DockerMvc/Controllers/CategoriaController.cs
using System.Threading.Tasks;
using DockerMvc.Interface;
using DockerMvc.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DockerMvc.Controllers
{
    [Authorize(Policy = "Admin")]
    public class CategoriaController : Controller
    {
        private readonly ICategoriaService _categoriaService;

        public CategoriaController(ICategoriaService categoriaService)
        {
            _categoriaService = categoriaService;
        }

        public async Task<IActionResult> Index()
        {
            var categorias = await _categoriaService.GetCategoriasAsync();
            return View(categorias);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                await _categoriaService.CreateCategoriaAsync(categoria);
                TempData["mensaje"] = "La categoría se agregó correctamente";
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var categoria = await _categoriaService.GetCategoriaByIdAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                await _categoriaService.UpdateCategoriaAsync(categoria);
                TempData["mensaje"] = "La categoría se actualizó correctamente";
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var categoria = await _categoriaService.GetCategoriaByIdAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _categoriaService.DeleteCategoriaAsync(id);
            TempData["mensaje"] = "La categoría se eliminó correctamente";
            return RedirectToAction(nameof(Index));
        }
    }
}

DockerMvc/Controllers/ProductosController.cs
using System.Threading.Tasks;
using DockerMvc.Interface;
using DockerMvc.Models;
using DockerMvc.ModelView;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DockerMvc.Controllers
{
    [Authorize(Policy = "Admin")]
    public class ProductosController : Controller
    {
        private readonly IProductoService _productoService;

        public ProductosController(IProductoService productoService)
        {
            _productoService = productoService;
        }

        public async Task<IActionResult> Index()
        {
            var productos = await _productoService.GetProductosAsync();
            return View(productos);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductosViewModel productos)
        {
            if (ModelState.IsValid)
            {
                var newProduct = new Productos
                {
                    Nombre = productos.Nombre,
                    Descripcion = productos.Descripcion,
                    Precio = productos.Precio,
                    Imagen = await _productoService.SaveImageAsync(productos.Imagen),
                    Stock = productos.Stock
                };
                await _productoService.AddProductoAsync(newProduct);
                TempData["mensaje"] = "El producto se agregó correctamente";
                return RedirectToAction("Index");
            }

            return View(productos);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var producto = await _productoService.GetProductoByIdAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            var productoViewModel = new ProductosViewModel
            {
                ProduId = producto.ProduId,
                Nombre = producto.Nombre,
                Descripcion = producto.Descripcion,
                Precio = producto.Precio,
                Stock = producto.Stock,
                Imagen = null // Aquí puedes cargar una vista previa si lo deseas
            };

            return View(productoViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductosViewModel productos)
        {
            if (ModelState.IsValid)
            {
                var producto = await _productoService.GetProductoByIdAsync(productos.ProduId);
                if (producto == null)
                {
                    return NotFound();
                }

                producto.Nombre = productos.Nombre;
                producto.Descripcion = productos.Descripcion;
                producto.Precio = productos.Precio;
                producto.Stock = productos.Stock;

                if (productos.Imagen != null)
                {
                    producto.Imagen = await _productoService.UpdateImageAsync(productos.Imagen, producto.Imagen);
                }

                await _productoService.UpdateProductoAsync(producto);
                TempData["mensaje"] = "El producto se actualizó correctamente";
                return RedirectToAction("Index");
            }
            return View(productos);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var producto = await _productoService.GetProductoByIdAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _productoService.GetProductoByIdAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            await _productoService.DeleteProductoAsync(producto);
            TempData["mensaje"] = "El producto se eliminó correctamente";
            return RedirectToAction("Index");
        }
    }
}

DockerMvc/Controllers/SubCategoriaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DockerMvc.Data;
using DockerMvc.Interface;
using DockerMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DockerMvc.Controllers
{
    public class SubCategoriaController : Controller
    {
        private readonly BaseDbContext _context;
        private readonly ISubCategoriaService _subCategoriaService;

        public SubCategoriaController(BaseDbContext context, ISubCategoriaService subCategoriaService)
        {
            _context = context;
            _subCategoriaService = subCategoriaService;
        }

        public async Task<IActionResult> Index()
        {
            var subCategorias = await _subCategoriaService.GetSubCategoriasAsync();
            return View(subCategorias);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Categorias = new SelectList(await _context.Categorias.ToListAsync(), "CatId", "Name");
            ViewBag.Productos = await _context.Productos.Select(p => new SelectListItem
            {
                Value = p.ProduId.ToString(),
                Text = p.Nombre
            }).ToListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SubCategoria subCategoria, List<int> selectedProducts)
        {
            if (ModelState.IsValid)
            {
                subCategoria.SubCategoriaProductos = new List<SubCategoriaProducto>();

                foreach (var productId in selectedProducts)
                {
                    subCategoria.SubCategoriaProductos.Add(new SubCategoriaProducto
                    {
                        ProductoId = productId,
                        SubCategoriaSubId = subCategoria.SubId
                    });
                }

                await _subCategoriaService.CreateSubCategoriaAsync(subCategoria);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categorias = new SelectList(await _context.Categorias.ToListAsync(), "CatId", "Name", subCategoria.CatId);
            ViewBag.Productos = await _context.Productos.Select(p => new SelectListItem
            {
                Value = p.ProduId.ToString(),
                Text = p.Nombre
            }).ToListAsync();
            return View(subCategoria);
        }



    }
}

DockerMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - DockerMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css" />
</head>
<body>
@{
    var currentUrl = Context.Request.Path.Value.ToLower();
    var isLoginPage = currentUrl.Contains("/account/login");
}
@if (!isLoginPage)
{
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DockerMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SubCategoria" asp-action="Index">SubCategorías</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
}
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - DockerMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>